default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    update_code_signing_settings(
        code_sign_identity: "iPhone Distribution",
        profile_name: "match AppStore com.fleetmap.fleetmanager"
    )
    build_app
    api_key = app_store_connect_api_key(key_id: "6BZAC5HXRJ")
    upload_to_testflight(api_key: api_key, skip_waiting_for_build_processing: true)
  end
end
